stages:
  - build
  - test-gcc
  - test-llvm
  - test-lang

build-luci:
  image: inf4/stubs:gcc-x64
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make all
  artifacts:
    paths:
      - "ld-luci-*.so"
      - "versions.txt"
  retry: 1

fetch-artifacts:
  image: busybox
  stage: build
  script:
    - rm -rf bean
    - mkdir -p bean/elfo
    - 'wget --no-check-certificate -O elfo-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2Felfo/jobs/artifacts/master/download?job=gcc"'
    - unzip -jo elfo-artifacts.zip -d bean/elfo
    - 'wget --no-check-certificate -O bean-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2Fbean/jobs/artifacts/master/download?job=build"'
    - unzip -jo bean-artifacts.zip -d bean
  artifacts:
    paths:
      - "bean/elfo/elfo-*"
      - "bean/bean-*"
  retry: 1

check-style:
  image: inf4/stubs:clang-x64
  stage: build
  before_script:
    - apt-get update && apt-get install -y python3 python3-pyparsing libc++-dev cpplint
  script:
    - make lint
    - make tidy


.test-gcc:
  stage: test-gcc
  dependencies:
    - build-luci
    - fetch-artifacts
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 1

test-debian-stretch-gcc:
  image: heinloth/lp-build:debian-stretch
  extends: .test-gcc

test-debian-buster-gcc:
  image: heinloth/lp-build:debian-buster
  extends: .test-gcc

test-debian-bullseye-gcc:
  image: heinloth/lp-build:debian-bullseye
  extends: .test-gcc

test-debian-bookworm-gcc:
  image: heinloth/lp-build:debian-bookworm
  extends: .test-gcc

test-ubuntu-focal-gcc:
  image: heinloth/lp-build:ubuntu-focal
  extends: .test-gcc

test-ubuntu-jammy-gcc:
  image: heinloth/lp-build:ubuntu-jammy
  extends: .test-gcc

test-almalinux-9-gcc:
  image: heinloth/lp-build:almalinux-9
  extends: .test-gcc

test-oraclelinux-9-gcc:
  image: heinloth/lp-build:oraclelinux-9
  extends: .test-gcc

test-rhel-9-gcc:
  image: heinloth/lp-build:rhel-9
  extends: .test-gcc

test-fedora-36-gcc:
  image: heinloth/lp-build:fedora-36
  extends: .test-gcc

test-fedora-37-gcc:
  image: heinloth/lp-build:fedora-37
  extends: .test-gcc

test-opensuseleap-15-gcc:
  image: heinloth/lp-build:opensuseleap-15
  extends: .test-gcc


.test-llvm:
  stage: test-llvm
  dependencies:
    - build-luci
    - fetch-artifacts
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 1

test-debian-stretch-llvm:
  image: heinloth/lp-build:debian-stretch
  extends: .test-llvm

test-debian-buster-llvm:
  image: heinloth/lp-build:debian-buster
  extends: .test-llvm

test-debian-bullseye-llvm:
  image: heinloth/lp-build:debian-bullseye
  extends: .test-llvm

test-debian-bookworm-llvm:
  image: heinloth/lp-build:debian-bookworm
  extends: .test-llvm

test-ubuntu-focal-llvm:
  image: heinloth/lp-build:ubuntu-focal
  extends: .test-llvm

test-ubuntu-jammy-llvm:
  image: heinloth/lp-build:ubuntu-jammy
  extends: .test-llvm

test-almalinux-9-llvm:
  image: heinloth/lp-build:almalinux-9
  extends: .test-llvm

test-oraclelinux-9-llvm:
  image: heinloth/lp-build:oraclelinux-9
  extends: .test-llvm

test-rhel-9-llvm:
  image: heinloth/lp-build:rhel-9
  extends: .test-llvm

test-fedora-36-llvm:
  image: heinloth/lp-build:fedora-36
  extends: .test-llvm

test-fedora-37-llvm:
  image: heinloth/lp-build:fedora-37
  extends: .test-llvm

test-opensuseleap-15-llvm:
  image: heinloth/lp-build:opensuseleap-15
  extends: .test-llvm


.test-lang:
  stage: test-lang
  dependencies:
    - build-luci
    - fetch-artifacts
  script:
    - ./test/run.sh -g lang -R
    - ./test/run.sh -g lang
    - ./test/run.sh -g lang -u
  retry: 1

test-debian-stretch-lang:
  image: heinloth/lp-build:debian-stretch
  extends: .test-lang

test-debian-buster-lang:
  image: heinloth/lp-build:debian-buster
  extends: .test-lang

test-debian-bullseye-lang:
  image: heinloth/lp-build:debian-bullseye
  extends: .test-lang

test-debian-bookworm-lang:
  image: heinloth/lp-build:debian-bookworm
  extends: .test-lang

test-ubuntu-focal-lang:
  image: heinloth/lp-build:ubuntu-focal
  extends: .test-lang

test-ubuntu-jammy-lang:
  image: heinloth/lp-build:ubuntu-jammy
  extends: .test-lang