stages:
  - build
  - test

build-luci:
  image: inf4/stubs:gcc-x64
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make all
  artifacts:
    paths:
      - "ld-luci-*.so"
  retry: 1

fetch-artifacts:
  image: busybox
  stage: build
  script:
    - rm -rf bean
    - mkdir -p bean/elfo
    - 'wget --no-check-certificate -O elfo-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2Felfo/jobs/artifacts/master/download?job=build-test"'
    - unzip -jo elfo-artifacts.zip -d bean/elfo
    - 'wget --no-check-certificate -O bean-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2Fbean/jobs/artifacts/master/download?job=build"'
    - unzip -jo bean-artifacts.zip -d bean
  artifacts:
    paths:
      - "bean/elfo/elfo-*"
      - "bean/bean-*"
  retry: 1

test-debian-stretch-gcc:
  image: debian:stretch
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make libcap2-bin
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-debian-buster-gcc:
  image: debian:buster
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make libcap2-bin
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-debian-bullseye-gcc:
  image: debian:bullseye
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make libcap2-bin
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-ubuntu-focal-gcc:
  image: ubuntu:focal
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make libcap2-bin
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-ubuntu-jammy-gcc:
  image: ubuntu:jammy
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make libcap2-bin
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-debian-stretch-llvm:
  image: debian:stretch
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang-11 make libcap2-bin
    - update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 110 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-11
    - update-alternatives --install /usr/bin/cc cc /usr/bin/clang 110 --slave /usr/bin/c++ c++ /usr/bin/clang++
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 2

test-debian-buster-llvm:
  image: debian:buster
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang make libcap2-bin
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 2

test-debian-bullseye-llvm:
  image: debian:bullseye
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang make libcap2-bin
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 2

test-ubuntu-focal-llvm:
  image: ubuntu:focal
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang make libcap2-bin
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 2

test-ubuntu-jammy-llvm:
  image: ubuntu:jammy
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang make libcap2-bin
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 2
