stages:
  - build
  - test-gcc
  - test-gcc-build
  - test-llvm
  - test-lang

build-luci:
  image: inf4/luci:ubuntu-jammy
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make all
  artifacts:
    paths:
      - "ld-luci-*.so"
      - "versions.txt"
  retry: 2

fetch-artifacts:
  image: busybox:latest
  stage: build
  script:
    - rm -rf bean
    - mkdir -p bean/elfo
    - 'wget --no-check-certificate -O elfo-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2Felfo/jobs/artifacts/master/download?job=gcc"'
    - unzip -jo elfo-artifacts.zip -d bean/elfo
    - 'wget --no-check-certificate -O bean-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_NAMESPACE}%2Fbean/jobs/artifacts/master/download?job=gcc"'
    - unzip -jo bean-artifacts.zip -d bean
  artifacts:
    paths:
      - "bean/elfo/elfo-*"
      - "bean/bean-*"
  retry: 2

check-style:
  image: inf4/luci:ubuntu-jammy
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make lint
    - make tidy

.test-gcc:
  stage: test-gcc
  dependencies:
    - build-luci
    - fetch-artifacts
  script:
    - ./test/run.sh -c GCC -R
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-debian-stretch-gcc:
  image: inf4/luci:debian-stretch
  extends: .test-gcc

test-debian-buster-gcc:
  image: inf4/luci:debian-buster
  extends: .test-gcc

test-debian-bullseye-gcc:
  image: inf4/luci:debian-bullseye
  extends: .test-gcc

test-debian-bookworm-gcc:
  image: inf4/luci:debian-bookworm
  extends: .test-gcc

test-ubuntu-focal-gcc:
  image: inf4/luci:ubuntu-focal
  extends: .test-gcc

test-ubuntu-jammy-gcc:
  image: inf4/luci:ubuntu-jammy
  extends: .test-gcc

test-almalinux-9-gcc:
  image: inf4/luci:almalinux-9
  extends: .test-gcc

test-oraclelinux-9-gcc:
  image: inf4/luci:oraclelinux-9
  extends: .test-gcc

test-rhel-9-gcc:
  image: inf4/luci:rhel-9
  extends: .test-gcc

test-fedora-36-gcc:
  image: inf4/luci:fedora-36
  extends: .test-gcc

test-fedora-37-gcc:
  image: inf4/luci:fedora-37
  extends: .test-gcc

test-opensuseleap-15-gcc:
  image: inf4/luci:opensuseleap-15
  extends: .test-gcc


# We have to remove capabilities since CI container have not sufficient permissions and userfaultfd would fail.
.test-gcc-build:
  stage: test-gcc-build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  dependencies:
    - fetch-artifacts
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:make[collapsed=true]\r\e[0KBuilding Luci"
    - make
    - setcap -r ld-luci-*.so || true
    - echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u
  retry: 2

test-debian-buster-gcc-build:
  image: inf4/luci:debian-buster
  extends: .test-gcc-build

test-debian-bullseye-gcc-build:
  image: inf4/luci:debian-bullseye
  extends: .test-gcc-build

test-debian-bookworm-gcc-build:
  image: inf4/luci:debian-bookworm
  extends: .test-gcc-build

test-ubuntu-focal-gcc-build:
  image: inf4/luci:ubuntu-focal
  extends: .test-gcc-build

test-ubuntu-jammy-gcc-build:
  image: inf4/luci:ubuntu-jammy
  extends: .test-gcc-build

test-almalinux-9-gcc-build:
  image: inf4/luci:almalinux-9
  extends: .test-gcc-build

test-oraclelinux-9-gcc-build:
  image: inf4/luci:oraclelinux-9
  extends: .test-gcc-build

test-rhel-9-gcc-build:
  image: inf4/luci:rhel-9
  extends: .test-gcc-build

test-fedora-36-gcc-build:
  image: inf4/luci:fedora-36
  extends: .test-gcc-build

test-fedora-37-gcc-build:
  image: inf4/luci:fedora-37
  extends: .test-gcc-build


.test-llvm:
  stage: test-llvm
  dependencies:
    - build-luci
    - fetch-artifacts
  script:
    - ./test/run.sh -c LLVM -R
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
  retry: 2

test-debian-stretch-llvm:
  image: inf4/luci:debian-stretch
  extends: .test-llvm

test-debian-buster-llvm:
  image: inf4/luci:debian-buster
  extends: .test-llvm

test-debian-bullseye-llvm:
  image: inf4/luci:debian-bullseye
  extends: .test-llvm

test-debian-bookworm-llvm:
  image: inf4/luci:debian-bookworm
  extends: .test-llvm

test-ubuntu-focal-llvm:
  image: inf4/luci:ubuntu-focal
  extends: .test-llvm

test-ubuntu-jammy-llvm:
  image: inf4/luci:ubuntu-jammy
  extends: .test-llvm

test-almalinux-9-llvm:
  image: inf4/luci:almalinux-9
  extends: .test-llvm

test-oraclelinux-9-llvm:
  image: inf4/luci:oraclelinux-9
  extends: .test-llvm

test-rhel-9-llvm:
  image: inf4/luci:rhel-9
  extends: .test-llvm

test-fedora-36-llvm:
  image: inf4/luci:fedora-36
  extends: .test-llvm

test-fedora-37-llvm:
  image: inf4/luci:fedora-37
  extends: .test-llvm

test-opensuseleap-15-llvm:
  image: inf4/luci:opensuseleap-15
  extends: .test-llvm


.test-lang:
  stage: test-lang
  dependencies:
    - build-luci
    - fetch-artifacts
  script:
    - ./test/run.sh -g lang -R
    - ./test/run.sh -g lang
    - ./test/run.sh -g lang -u
  retry: 2

test-debian-stretch-lang:
  image: inf4/luci:debian-stretch
  extends: .test-lang

test-debian-buster-lang:
  image: inf4/luci:debian-buster
  extends: .test-lang

test-debian-bullseye-lang:
  image: inf4/luci:debian-bullseye
  extends: .test-lang

test-debian-bookworm-lang:
  image: inf4/luci:debian-bookworm
  extends: .test-lang

test-ubuntu-focal-lang:
  image: inf4/luci:ubuntu-focal
  extends: .test-lang

test-ubuntu-jammy-lang:
  image: inf4/luci:ubuntu-jammy
  extends: .test-lang
