stages:
  - build
  - test

build-luci:
  image: inf4/stubs:gcc-x64
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make all
  artifacts:
    paths:
      - "ld-luci-*.so"

fetch-artifacts:
  image: busybox
  stage: build
  script:
    - rm -rf bean
    - mkdir -p bean/elfo
    - 'wget -O elfo-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/13125/jobs/artifacts/master/download?job=build-test"'
    - unzip -jo elfo-artifacts.zip -d bean/elfo
    - 'wget -O bean-artifacts.zip --header="JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/13236/jobs/artifacts/master/download?job=build"'
    - unzip -jo bean-artifacts.zip -d bean
  artifacts:
    paths:
      - "bean/elfo/elfo-*"
      - "bean/example-*"

test-debian-stretch-gcc:
  image: debian:stretch
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make
  script:
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u

test-ubuntu-focal-gcc:
  image: ubuntu:focal
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y gcc g++ make
  script:
    - ./test/run.sh -c GCC
    - ./test/run.sh -c GCC -u

test-debian-stretch-llvm:
  image: debian:stretch
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang-11 make
    - update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 110 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-11
    - update-alternatives --install /usr/bin/cc cc /usr/bin/clang 110 --slave /usr/bin/c++ c++ /usr/bin/clang++
  script:
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u

test-ubuntu-focal-llvm:
  image: ubuntu:focal
  stage: test
  dependencies:
    - build-luci
    - fetch-artifacts
  before_script:
    - apt-get update && apt-get install -y clang make
  script:
    - ./test/run.sh -c LLVM
    - ./test/run.sh -c LLVM -u
