DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
CC=gcc
#CFLAGS=-O2 -Wall -nostdlib -mcmodel=large -fomit-frame-pointer -fno-exceptions -fno-asynchronous-unwind-tables -fno-unwind-tables
#LDFLAGS=-nostdlib -mcmodel=large -ffreestanding -L. -Wl,-rpath=$(DIR)
CFLAGS=-O2 -g -Wall -nostdlib -fno-exceptions
LDFLAGS=-nostdlib -L. -ffreestanding  -Wl,-rpath=$(DIR) -Wl,--dynamic-linker=/opt/luci/ld-luci.so
LIBS=sys util
SOURCE=start.c hello.c
OBJECTS=$(SOURCE:.c=.o)
BINARY=test-so

all: $(BINARY)

$(BINARY): $(OBJECTS) | $(addprefix lib,$(addsuffix .so,$(LIBS))) $(addprefix libutil.so.,0 1 2 3 4 5 6 7 8)
	$(CC) $(LDFLAGS) -o $@ $^ $(addprefix -l,$(LIBS))

lib%.so: %.c Makefile
	$(CC) $(CFLAGS) -fPIC --shared -o $@ $<

libutil.so.%: util.c Makefile
	$(CC) $(CFLAGS) -DVERSION=$* -fPIC --shared -o $@ $<

%.o: %.c Makefile
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS)

mrproper: clean
	rm -f $(BINARY)

.PHONY: all clean mrproper
