DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
CC=gcc
CFLAGS=-Og -g -nostdlib -static
LDFLAGS=--dynamic-linker=$(realpath $(DIR)/../../luci)
SOURCE=sys.c start.c hello.c
OBJECTS=$(SOURCE:.c=.o)
BINARY=test-static

all: $(BINARY)

$(BINARY): $(OBJECTS)
	ld $(LDFLAGS) -o $@ $^

%.o: %.c Makefile
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS)

mrproper: clean
	rm -f $(BINARY)

.PHONY: all clean mrproper
