DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
CC=gcc
CFLAGS=-Og -g -Wall -nostdlib -mcmodel=large
LDFLAGS=-nostdlib -mcmodel=large -ffreestanding -L. -Wl,-rpath=$(DIR) -Wl,--dynamic-linker=$(realpath $(DIR)/../../luci)
LIBS=sys
SOURCE=start.c hello.c
OBJECTS=$(SOURCE:.c=.o)
BINARY=test-so

all: $(BINARY)

$(BINARY): $(OBJECTS) | $(addprefix lib,$(addsuffix .so,$(LIBS)))
	$(CC) $(LDFLAGS) -o $@ $^ $(addprefix -l,$(LIBS))

lib%.so: %.c Makefile
	$(CC) $(CFLAGS) -fPIC --shared -o $@ $<

%.o: %.c Makefile
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS)

mrproper: clean
	rm -f $(BINARY)

.PHONY: all clean mrproper
